add_newline = false
command_timeout = 800
format = "$directory$git_branch$git_status$character"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = " [$branch]($style)"
style = "bold"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "dimmed"

[character]
success_symbol = "❯"
error_symbol = "❯"

