add_newline = true
command_timeout = 800

format = """
$directory$git_branch$git_status$status
$character
"""

[directory]
style = "bold"
truncate_to_repo = true
truncation_length = 3
format = "[$path]($style)"

[git_branch]
format = "  [$symbol$branch]($style)"
symbol = "⎇ "
style = "bold"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "dimmed"
conflicted = "≠"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "?"
stashed = "*"
modified = "!"
staged = "+"
renamed = "»"
deleted = "x"

[character]
success_symbol = "❯ "
error_symbol = "❯ "

[hostname]
ssh_only = true
format = " [$hostname]($style)"
style = "dimmed"

[status]
disabled = false
format = " [$status]($style)"
style = "bold"

[cmd_duration]
min_time = 1500
format = " [$duration]($style)"
style = "dimmed"

